Repository egypt-shops/xshop-web, pull requests merged in 2020-10, with the labels that each got.

#16 Change Django Admin Skin
  poetry.lock
  project/settings.py
  pyproject.toml
Labels: enhancement

#17 Showing token inline UserAdmin in the dashboard
  xshop/users/admin.py
  xshop/users/tests/test_models.py
Labels: enhancement

#12 Detailed Design Stage 1
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/xshop-web.iml
  README.md
  poetry.lock
  project/settings.py
  pyproject.toml
  xshop/core/migrations/0001_initial.py
  xshop/core/migrations/0002_pricingplan.py
  xshop/core/migrations/0003_product.py
  xshop/core/migrations/0004_auto_20201005_1509.py
  xshop/core/migrations/0005_product_shop.py
  xshop/core/migrations/0006_order_orderitem.py
  xshop/core/migrations/0007_invoice.py
  xshop/core/models.py
  xshop/users/managers.py
  xshop/users/migrations/0002_user_type.py
  xshop/users/migrations/0003_auto_20201003_0833.py
  xshop/users/models.py
  xshop/users/tests/test_models.py
Labels: new

#26 Swagger-UI Added
  project/urls.py
  templates/pages/swagger-ui.html
  xshop/pages/views.py
Labels: new

#35 Login web page Added
  poetry.lock
  project/settings.py
  project/urls.py
  pyproject.toml
  templates/base.html
  templates/pages/home.html
  templates/registration/login.html
  xshop/pages/tests/test_views.py
Labels: new

#54 Adding basic CRUD operations for product endpoint
  project/settings.py
  project/urls.py
  xshop/core/api/__init__.py
  xshop/core/api/serializers.py
  xshop/core/api/urls.py
  xshop/core/api/views.py
  xshop/core/tests/test_api.py
  xshop/core/urls.py
Labels: new

#43 Better Admin Dashboard
  api.http
  poetry.lock
  project/settings.py
  pyproject.toml
  templates/admin/auth/user/add_form.html
  templates/base.html
  templates/pages/swagger_ui.html
  templates/registration/login.html
  xshop/core/admin.py
  xshop/core/migrations/0008_order_paid.py
  xshop/core/models.py
  xshop/pages/tests/test_views.py
  xshop/users/admin.py
  xshop/users/models.py
  xshop/users/tests/test_admin.py
  xshop/users/tests/test_managers.py
  xshop/users/tests/test_services.py
Labels: enhancement, new

#75 Extending product api "filter method to filter product_list with query param shop_id"
  xshop/products/api/urls.py
  xshop/products/api/views.py
  xshop/products/tests/test_api/test_views.py
Labels: enhancement

#76 Adding Shop Detail API "GET"
  project/urls.py
  xshop/shops/api/serializers.py
  xshop/shops/api/urls.py
  xshop/shops/api/views.py
  xshop/shops/tests/test_api/test_views.py
Labels: enhancement

#82 Replacing old swagger ui with drf-yasg2 for better ui and easy customization
  poetry.lock
  project/settings.py
  pyproject.toml
  templates/pages/swagger_ui.html
  xshop/pages/api/urls.py
  xshop/pages/api/views.py
  xshop/pages/tests/test_api/test_views.py
  xshop/products/api/views.py
  xshop/shops/api/views.py
  xshop/users/api/serializers.py
  xshop/users/api/views.py
Labels: enhancement
