Repository egypt-shops/xshop-web, pull requests merged in 2021-04, with the labels that each got.

#150 Switch from drf-yasg2 to drf-spectacular
  poetry.lock
  project/settings.py
  pyproject.toml
  xshop/cart/api/views.py
  xshop/invoices/api/views.py
  xshop/orders/api/views.py
  xshop/pages/api/urls.py
  xshop/products/api/views.py
  xshop/shops/api/views.py
  xshop/users/api/views.py
Labels: enhancement

#151 List Products per shop
  xshop/products/api/urls.py
  xshop/products/api/views.py
  xshop/products/tests/test_api/test_views.py
Labels: new

#144 Export manager products
  xshop/products/admin.py
  xshop/products/tests/test_admin.py
Labels: enhancement

#157 Update Django to 3.2
  poetry.lock
  pyproject.toml
Labels: enhancement

#154 api for POST checkout
  xshop/orders/api/serializers.py
  xshop/orders/api/urls.py
  xshop/orders/api/views.py
  xshop/orders/models.py
  xshop/orders/tests/test_api/test_serializers.py
  xshop/orders/tests/test_api/test_views.py
Labels: e-commerce
